[colors.bright]
black = "#939cc2"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#61ffe2"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#4fd6be"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#222436"
foreground = "#c8d3f5"
